#!/usr/bin/env python3
"""
Piper TTS provider implementation.
"""

from pathlib import Path
import subprocess
import threading
import numpy as np
import sounddevice as sd
from typing import Optional, Dict, Any
from tts_interface import TTSProvider, TTSError


class PiperTTSProvider(TTSProvider):
    """Piper TTS provider using local ONNX models."""
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__(config)
        
        # Default configuration
        script_dir = Path(__file__).parent.resolve()
        self.script_dir = self.config.get('script_dir', str(script_dir))
        self.piper_bin = self.config.get('piper_bin', 
                                         str(Path(self.script_dir) / "venv" / "bin" / "piper"))
        self.model_path = self.config.get('model_path',
                                          str(Path(self.script_dir) / "en_US-lessac-medium"))
        self.sample_rate = self.config.get('sample_rate', 22050)
        
        # Playback state
        self._lock = threading.Lock()
        self._audio_data: Optional[np.ndarray] = None
        self._playback_position = 0
        self._is_playing = False
        self._is_paused = False
        self._stream: Optional[sd.OutputStream] = None
        self._finished_event = threading.Event()
    
    @property
    def name(self) -> str:
        return "Piper TTS"
    
    def validate_config(self) -> bool:
        """Check if piper binary and model exist."""
        if not Path(self.piper_bin).exists():
            return False
        if not Path(f"{self.model_path}.onnx").exists():
            return False
        return True
    
    def speak(self, text: str) -> None:
        """Speak text using Piper and sounddevice (non-blocking)."""
        # Stop any current playback
        self.stop()
        
        try:
            # Generate audio with piper
            piper_process = subprocess.Popen(
                [self.piper_bin, "--model", self.model_path, "--output_file", "-"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            
            # Send text to piper
            piper_process.stdin.write(text.encode('utf-8'))
            piper_process.stdin.close()
            
            # Read audio data (raw PCM, 16-bit signed little-endian, mono)
            audio_bytes = piper_process.stdout.read()
            piper_process.stdout.close()
            
            # Wait for piper to complete
            piper_process.wait()
            
            # Check for errors
            if piper_process.returncode != 0:
                stderr_output = piper_process.stderr.read().decode('utf-8', errors='ignore')
                raise TTSError(f"Piper process failed with code {piper_process.returncode}: {stderr_output}")
            
            if not audio_bytes:
                raise TTSError("No audio data generated by Piper")
            
            # Convert bytes to numpy array (int16, then normalize to float32)
            audio_int16 = np.frombuffer(audio_bytes, dtype=np.int16)
            # Normalize to float32 range [-1.0, 1.0]
            self._audio_data = audio_int16.astype(np.float32) / 32768.0
            
            # Reset playback state
            with self._lock:
                self._playback_position = 0
                self._is_playing = False
                self._is_paused = False
                self._finished_event.clear()
            
            # Start playback
            self._start_stream()
                
        except subprocess.SubprocessError as e:
            raise TTSError(f"Subprocess error during speech: {e}") from e
        except Exception as e:
            if isinstance(e, TTSError):
                raise
            raise TTSError(f"Error during speech: {e}") from e
    
    def _audio_callback(self, outdata, frames, time_info, status):
        """Callback for OutputStream - feeds audio data continuously."""
        if self._audio_data is None:
            outdata.fill(0)
            return
        
        with self._lock:
            start = self._playback_position
            end = start + frames
            
            if start >= len(self._audio_data):
                # Finished playing
                outdata.fill(0)
                self._finished_event.set()
                raise sd.CallbackStop()
            
            # Get available data
            available = len(self._audio_data) - start
            to_copy = min(frames, available)
            
            # Copy audio data to output buffer
            outdata[:to_copy, 0] = self._audio_data[start:start + to_copy]
            
            # Zero-fill any remaining frames
            if to_copy < frames:
                outdata[to_copy:] = 0
                self._finished_event.set()
                raise sd.CallbackStop()
            
            # Update position
            self._playback_position = end
    
    def _start_stream(self) -> None:
        """Start the audio output stream."""
        if self._audio_data is None:
            return
        
        with self._lock:
            self._is_playing = True
            self._is_paused = False
        
        try:
            self._stream = sd.OutputStream(
                samplerate=self.sample_rate,
                channels=1,
                dtype='float32',
                callback=self._audio_callback,
                finished_callback=self._on_stream_finished
            )
            self._stream.start()
        except Exception as e:
            with self._lock:
                self._is_playing = False
            raise TTSError(f"Failed to start audio stream: {e}") from e
    
    def _on_stream_finished(self) -> None:
        """Called when the stream finishes playing."""
        with self._lock:
            # Only reset state if not paused (paused means intentional stop)
            if not self._is_paused:
                self._is_playing = False
    
    def pause(self) -> None:
        """Pause the current speech playback."""
        with self._lock:
            if not self._is_playing or self._is_paused:
                return
            self._is_paused = True
        
        try:
            if self._stream and self._stream.active:
                self._stream.stop()
        except Exception as e:
            raise TTSError(f"Error pausing playback: {e}") from e
    
    def resume(self) -> None:
        """Resume paused speech playback."""
        with self._lock:
            if not self._is_paused or self._audio_data is None:
                return
            self._is_paused = False
        
        try:
            # Create a new stream from current position
            self._start_stream()
        except Exception as e:
            raise TTSError(f"Error resuming playback: {e}") from e
    
    def stop(self) -> None:
        """Stop the current speech playback."""
        try:
            if self._stream:
                self._stream.stop()
                self._stream.close()
                self._stream = None
        except Exception:
            pass  # Ignore errors when stopping
        
        with self._lock:
            self._is_playing = False
            self._is_paused = False
            self._playback_position = 0
    
    def is_playing(self) -> bool:
        """Check if speech is currently playing."""
        with self._lock:
            return self._is_playing and not self._is_paused
    
    def is_paused(self) -> bool:
        """Check if speech is currently paused."""
        with self._lock:
            return self._is_paused

