#!/usr/bin/env python3
"""
Piper TTS provider implementation.
"""

from pathlib import Path
import subprocess
import threading
import numpy as np
import sounddevice as sd
from typing import Optional, Dict, Any
from tts_interface import TTSProvider, TTSError


class PiperTTSProvider(TTSProvider):
    """Piper TTS provider using local ONNX models."""
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__(config)
        
        # Default configuration
        script_dir = Path(__file__).parent.resolve()
        self.script_dir = Path(self.config.get('script_dir', script_dir))
        self.piper_bin = Path(self.config.get('piper_bin', 
                                               self.script_dir / "venv" / "bin" / "piper"))
        self.model_path = Path(self.config.get('model_path',
                                                self.script_dir / "en_US-lessac-medium"))
        self.sample_rate = self.config.get('sample_rate', 22050)
        
        # Playback state
        self._lock = threading.Lock()
        self._audio_data: Optional[np.ndarray] = None
        self._playback_position = 0
        self._is_playing = False
        self._is_paused = False
        self._stream: Optional[sd.OutputStream] = None
        self._finished_event = threading.Event()
        self._current_chunk: Optional[np.ndarray] = None  # For visualization
    
    @property
    def name(self) -> str:
        return "Piper TTS"
    
    def validate_config(self) -> bool:
        """Check if piper binary and model exist."""
        return (self.piper_bin.exists() and 
                self.model_path.with_suffix('.onnx').exists())
    
    def speak(self, text: str) -> None:
        """Speak text using Piper and sounddevice (non-blocking)."""
        # Stop any current playback
        self.stop()
        
        try:
            # Generate audio with piper
            piper_process = subprocess.Popen(
                [str(self.piper_bin), "--model", str(self.model_path), "--output_file", "-"],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
            
            # Send text to piper
            piper_process.stdin.write(text.encode('utf-8'))
            piper_process.stdin.close()
            
            # Read audio data (raw PCM, 16-bit signed little-endian, mono)
            audio_bytes = piper_process.stdout.read()
            piper_process.stdout.close()
            
            # Wait for piper to complete
            piper_process.wait()
            
            # Check for errors
            if piper_process.returncode != 0:
                stderr_output = piper_process.stderr.read().decode('utf-8', errors='ignore')
                raise TTSError(f"Piper process failed with code {piper_process.returncode}: {stderr_output}")
            
            if not audio_bytes:
                raise TTSError("No audio data generated by Piper")
            
            # Convert bytes to numpy array (int16, then normalize to float32)
            audio_int16 = np.frombuffer(audio_bytes, dtype=np.int16)
            # Normalize to float32 range [-1.0, 1.0]
            self._audio_data = audio_int16.astype(np.float32) / 32768.0
            
            # Reset playback state
            with self._lock:
                self._playback_position = 0
                self._is_playing = False
                self._is_paused = False
                self._finished_event.clear()
            
            # Start playback
            self._start_stream()
                
        except subprocess.SubprocessError as e:
            raise TTSError(f"Subprocess error during speech: {e}") from e
        except Exception as e:
            raise TTSError(f"Error during speech: {e}") from e
    
    def _audio_callback(self, outdata, frames, time_info, status):
        """Callback for OutputStream - feeds audio data continuously."""
        if self._audio_data is None:
            outdata.fill(0)
            return
        
        with self._lock:
            start = self._playback_position
            end = start + frames
            
            if start >= len(self._audio_data):
                # Finished playing
                outdata.fill(0)
                self._finished_event.set()
                raise sd.CallbackStop()
            
            # Get available data
            available = len(self._audio_data) - start
            to_copy = min(frames, available)
            
            # Copy audio data to output buffer
            outdata[:to_copy, 0] = self._audio_data[start:start + to_copy]
            
            # Store current chunk for visualization
            self._current_chunk = self._audio_data[start:start + to_copy].copy()
            
            # Zero-fill any remaining frames
            if to_copy < frames:
                outdata[to_copy:] = 0
                self._finished_event.set()
                raise sd.CallbackStop()
            
            # Update position
            self._playback_position = end
    
    def _start_stream(self) -> None:
        """Start the audio output stream."""
        if self._audio_data is None:
            return
        
        with self._lock:
            self._is_playing = True
            self._is_paused = False
        
        try:
            self._stream = sd.OutputStream(
                samplerate=self.sample_rate,
                channels=1,
                dtype='float32',
                callback=self._audio_callback,
                finished_callback=self._on_stream_finished
            )
            self._stream.start()
        except Exception as e:
            with self._lock:
                self._is_playing = False
            raise TTSError(f"Failed to start audio stream: {e}") from e
    
    def _on_stream_finished(self) -> None:
        """Called when the stream finishes playing."""
        with self._lock:
            # Only reset state if not paused (paused means intentional stop)
            if not self._is_paused:
                self._is_playing = False
    
    def pause(self) -> None:
        """Pause the current speech playback."""
        with self._lock:
            if not self._is_playing or self._is_paused:
                return
            self._is_paused = True
        
        try:
            if self._stream and self._stream.active:
                self._stream.stop()
        except Exception as e:
            raise TTSError(f"Error pausing playback: {e}") from e
    
    def resume(self) -> None:
        """Resume paused speech playback."""
        with self._lock:
            if not self._is_paused or self._audio_data is None:
                return
            self._is_paused = False
        
        try:
            # Create a new stream from current position
            self._start_stream()
        except Exception as e:
            raise TTSError(f"Error resuming playback: {e}") from e
    
    def _stop_stream(self) -> None:
        """Stop and close the audio stream. Ignores errors."""
        try:
            if self._stream:
                self._stream.stop()
                self._stream.close()
                self._stream = None
        except Exception:
            pass  # Ignore errors when stopping
    
    def stop(self) -> None:
        """Stop the current speech playback."""
        self._stop_stream()
        
        with self._lock:
            self._is_playing = False
            self._is_paused = False
            self._playback_position = 0
    
    def is_playing(self) -> bool:
        """Check if speech is currently playing."""
        with self._lock:
            return self._is_playing and not self._is_paused
    
    def is_paused(self) -> bool:
        """Check if speech is currently paused."""
        with self._lock:
            return self._is_paused
    
    def skip_forward(self, seconds: float) -> None:
        """Skip forward in the current speech playback."""
        if self._audio_data is None:
            return
        
        with self._lock:
            samples_to_skip = int(seconds * self.sample_rate)
            new_position = self._playback_position + samples_to_skip
            reached_end = new_position >= len(self._audio_data)
            
            # Clamp to end of audio
            self._playback_position = min(new_position, len(self._audio_data))
            
            if reached_end:
                # If we've reached the end, stop playback (reset both playing and paused states)
                self._is_playing = False
                self._is_paused = False
        
        # Stop stream if we reached the end
        if reached_end:
            self._stop_stream()
        
        # If playing, the callback will naturally pick up the new position
        # If paused, position is updated for next resume
    
    def skip_backward(self, seconds: float) -> None:
        """Skip backward in the current speech playback."""
        if self._audio_data is None:
            return
        
        with self._lock:
            samples_to_skip = int(seconds * self.sample_rate)
            new_position = self._playback_position - samples_to_skip
            # Clamp to start of audio
            self._playback_position = max(0, new_position)
        
        # If playing, the callback will naturally pick up the new position
        # If paused, position is updated for next resume
    
    def get_frequency_bands(self, num_bands: int = 10) -> list[float]:
        """Get frequency band amplitudes for visualization using FFT.
        
        Args:
            num_bands: Number of frequency bands to return
            
        Returns:
            List of normalized amplitude values (0.0-1.0) for each frequency band
        """
        with self._lock:
            # Return zeros if no current chunk or chunk too small
            if self._current_chunk is None or len(self._current_chunk) < 128:
                return [0.0] * num_bands
            
            chunk = self._current_chunk.copy()
        
        # Apply windowing to reduce spectral leakage
        window = np.hanning(len(chunk))
        windowed_chunk = chunk * window
        
        # Perform FFT to get frequency spectrum
        fft_data = np.fft.rfft(windowed_chunk)
        fft_magnitude = np.abs(fft_data)
        
        # Split into logarithmic frequency bands (more natural for audio)
        # Low frequencies get more resolution, high frequencies less
        bands = []
        
        if len(fft_magnitude) > num_bands:
            # Use logarithmic spacing for more natural frequency distribution
            band_edges = np.logspace(0, np.log10(len(fft_magnitude)), num_bands + 1)
            band_edges = band_edges.astype(int)
            
            for i in range(num_bands):
                start = band_edges[i]
                end = min(band_edges[i + 1], len(fft_magnitude))
                
                if end > start:
                    # Use RMS (root mean square) for better energy representation
                    band_energy = np.sqrt(np.mean(fft_magnitude[start:end] ** 2))
                    bands.append(float(band_energy))
                else:
                    bands.append(0.0)
        else:
            # Fallback for very small chunks
            bands = [float(x) for x in fft_magnitude[:num_bands]]
            bands.extend([0.0] * (num_bands - len(bands)))
        
        # Normalize to 0-1 range with dynamic scaling
        if bands and max(bands) > 0:
            max_val = max(bands)
            # Apply compression curve for better visualization
            bands = [(b / max_val) ** 0.7 for b in bands]  # Power curve for dynamic range
        
        return bands

